[package]
name = "nih_plug_iced"
version = "0.0.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"

description = "An adapter to use iced GUIs with NIH-plug"

[features]
default = []

# NOTE: wgpu support has been removed from the iced-baseview fork out because
#       this old iced version uses a wgpu version that doesn't pin the web-sys
#       version it uses, and web-sys broke semver
# # Use wgpu rendering, which translates to Vulkan, Metal, or Direct3D12 depending
# # on the platform.
# # NOTE: The OpenGL support in baseview is not used, this is just a workaround
# #       for a rust analyzer bug. See the comment in lib.rs.
# wgpu = ["iced_baseview/wgpu", "baseview/opengl"]
# Use OpenGL instead of wgpu for the rendering. This should increase platform
# compatibility at the cost of some iced features not being available.
# opengl = ["iced_baseview/glow"]

wgpu = ["iced_baseview/wgpu"]
# Enables the `Image` widget, only supported by the wgpu backend
image = ["iced_baseview/image"]
# Enables the `Svg` widget, only supported by the wgpu backend
svg = ["iced_baseview/svg"]
# Enables the `Canvas` widget for the wgpu backend
canvas = ["iced_baseview/canvas"]

[dependencies]
nih_plug = { path = "..", default_features = false }
nih_plug_assets = { git = "https://github.com/robbert-vdh/nih_plug_assets.git" }

# The currently targeted version of baseview uses a different version of
# `raw_window_handle` than NIH-plug, so we need to manually convert between them
raw-window-handle = "0.5"

atomic_refcell = "0.1"
# per https://github.com/robbert-vdh/nih-plug/pull/170#issuecomment-3158546796 ,
# this needs to reference a specific commit hash of baseview.
# TODO: Is this still the case? This is quite odd - why not reference a specific / newer version?
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "3724a00c970a9cd10a3494fa3c37bca66d631bb7" }
crossbeam = "0.8"
# per the above instructions,
# this needs to reference a specific branch in which changes were made
# to iced_baseview to support 0.14.
# HOWEVER: that PR references main branch of iced. Instead, we want to reference 0.14 for stability
# (which didn't exist at the time). So, I have ALSO forked iced_baseview to fix this, making it
# specifically point at 0.14 of iced. That's why the below points at one of my own forks.
iced_baseview = { git = "https://github.com/chairbender/iced_baseview.git", branch = "support-iced-0.14"}
futures-util = "0.3"

# To make the state persistable
serde = { version = "1.0", features = ["derive"] }
